### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by Skyqula** [jaquadro/BigDoors#1]
As the title says: crash when monsters die near/in/on a big door: http://pastebin.com/ddfm19Eq
Modlist: http://i.imgur.com/nPCZAUq.jpg

**Comment by jaquadro** [comment]
@Ordinastie The issue is a bit dated, but I would think applies the same at least to carraige doors, since that was the code I modeled after.

Do you know if this is something that was resolved in MalisisCore since this summer?

**Comment by Ordinastie** [comment]
Yes, it was resolved in a later update.

**Comment by jaquadro** [comment]
Thanks for confirming!
