### ISSUE TITLE
Block breaking animation is somehow transferring from nearby blocks to big doors

### ISSUE THREAD

**Issue by BBoldt** [jaquadro/BigDoors#2]
I don't even know:

https://dl.dropboxusercontent.com/u/134976541/ShareX/2015-08/2015-08-13_18-54-48.mp4

**Comment by jaquadro** [comment]
This was fixed really early but I completely failed to put out an updated release.  A new version is out now with the fix.

**Comment by BBoldt** [comment]
\o/

All my dreams have been fulfilled
